name: khaanabuddy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  google_generative_ai: ^0.4.7
  firebase_core: ^2.32.0
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1

  cloud_firestore: ^4.12.2
  shared_preferences: ^2.2.2
  youtube_player_flutter: ^9.0.4
  flutter_tts: ^3.6.3
  speech_to_text: ^7.0.0
  animated_splash_screen: ^1.3.0
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  http: ^1.1.0

  flutter_inappwebview: ^6.0.0
  firebase_storage: ^11.6.5
  image_picker: ^1.1.2
  

# ✅ Add this section to fix flutter_inappwebview namespace issue

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - "lib/assets/CookMate_logo.png"
    - "lib/assets/google_logo.png"

