// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuzZYu4owHA__o473pGVO-q3juFPDWvuc',
    appId: '1:215274115316:web:6ac72854d152ae4a3d0ea1',
    messagingSenderId: '215274115316',
    projectId: 'khaanabuddy-9fc4d',
    authDomain: 'khaanabuddy-9fc4d.firebaseapp.com',
    storageBucket: 'khaanabuddy-9fc4d.firebasestorage.app',
    measurementId: 'G-HH5C5NF46S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKWosQNSFqnbub1m6EdjrHE_XFOv8-ckA',
    appId: '1:215274115316:android:decc8555644653e13d0ea1',
    messagingSenderId: '215274115316',
    projectId: 'khaanabuddy-9fc4d',
    storageBucket: 'khaanabuddy-9fc4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDes1fN3W7J08SgWjr-9U9LFfBA29_kElg',
    appId: '1:215274115316:ios:0378856b660ab8bf3d0ea1',
    messagingSenderId: '215274115316',
    projectId: 'khaanabuddy-9fc4d',
    storageBucket: 'khaanabuddy-9fc4d.firebasestorage.app',
    iosBundleId: 'com.example.khaanabuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDes1fN3W7J08SgWjr-9U9LFfBA29_kElg',
    appId: '1:215274115316:ios:0378856b660ab8bf3d0ea1',
    messagingSenderId: '215274115316',
    projectId: 'khaanabuddy-9fc4d',
    storageBucket: 'khaanabuddy-9fc4d.firebasestorage.app',
    iosBundleId: 'com.example.khaanabuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuzZYu4owHA__o473pGVO-q3juFPDWvuc',
    appId: '1:215274115316:web:013fa6921a44b3183d0ea1',
    messagingSenderId: '215274115316',
    projectId: 'khaanabuddy-9fc4d',
    authDomain: 'khaanabuddy-9fc4d.firebaseapp.com',
    storageBucket: 'khaanabuddy-9fc4d.firebasestorage.app',
    measurementId: 'G-K8JP88SYE4',
  );
}
